### ISSUE TITLE
TODO  in order to bring the react template to production

### ISSUE THREAD

**Issue by nickbalestra** [opencomponents/oc-template-react#7]
- [x] [oc-template-react-compiler/lib/compile.js](https://github.com/opencomponents/oc-template-react/pull/6/files#diff-e1e886021803d3e024ccee5319076918) could be generalized into a base-template-utils, where the various compiler (view, statics, server) are passed upon initialization of the module. This will allow to reduce the duplication of code in both the react-template and the base templates together with allowing for faster development of templates. 👉  [PR](https://github.com/opencomponents/base-templates/pull/55)
- [x] compile should be able to understand [when run in dev](https://github.com/opentable/oc/blob/master/src/cli/facade/dev.js#L66) and in publish mode, allowing for faster and better debugging tools in dev, and more optimized bundle upon publishing. Rely on the minify: false for dev. 👉   [PR](https://github.com/opentable/oc/pull/613) 
- [x] extend [oc-webpack](https://github.com/opencomponents/base-templates/tree/master/packages/oc-webpack) to support a wider spectrum of scenarios, so that we can reduce the amount of code duplication in this template (ie return memoryFs instead of a single specific file). 👉   [PR](https://github.com/opencomponents/base-templates/pull/56)
- [x] create a generic compile statics file for greater reuse 👉   [PR](https://github.com/opencomponents/base-templates/pull/57)
- [x] decouple utils by moving them in an utils feature-branch for further development as per #14 
- [x] reuse the above within the react-template itself

**Comment by nickbalestra** [comment]
@matteofigus @mattiaerre once all the above PR are merged and the relative packages published we can dedupe some code in the react-template as well by reusing the ones above. I suggest we do this as a second PR/release and first proceede with an earlier relise of the react-template -> https://github.com/opencomponents/oc-template-react/pulls
